name: Build Flutter APK from ZIP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Change to a specific version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract ZIP file
        run: |
          unzip project.zip -d flutter_project

      - name: Print environment variables
        run: env  # Optional: for debugging

      - name: Set up Flutter
        uses: subosito/flutter-action@v3  # Use the latest version
        with:
          flutter-version: '3.7.0'  # Replace with the latest stable version

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: |
          cd flutter_project
          flutter pub get

      - name: Build APK
        run: |
          cd flutter_project
          flutter build apk --release --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: flutter_project/build/app/outputs/flutter-apk/app-release-*.apk
